### ISSUE TITLE
Game crashing upon startup

### ISSUE THREAD

**Issue by CleansedBlade** [HarbourMasters/Starship#100]
My game is crashing upon startup giving these error messages
[Starship.log](https://github.com/user-attachments/files/18279313/Starship.log)
I've tried a few things including re-extracting the files, regenerating the otr, and running as administrator just in case but nothing seems to work.  Is there something I'm doing wrong? 

Thanks!

**Comment by KiritoDv** [comment]
Try to follow discord support instructions but its probably that it failed to load the main game otr, try installing vcredist and retry

**Comment by CleansedBlade** [comment]
Hey thanks! Instructions on discord did indeed help. I installed vcredist but hadn't restarted and once I did it worked.

Thanks again!
