### ISSUE TITLE
Nintendo 64 switch controller mapped incorrectly

### ISSUE THREAD

**Issue by TheHeroEvans** [HarbourMasters/Starship#33]
By default, R button does nothing and see C↓ tilts the arwing right. The game lets you remap your controls, but even after remapping to be faithful to the original, C↓ *still* tilts the Arwing to the right while also breaking.

**Comment by Gurkgamer** [comment]
I had this problem. When remapping, the buttons selected wouldn't show up either. After restarting, old and new mappings showed up and I was able to remove the previous ones that I didn't like. Try restarting to see if there is any luck!

**Comment by TheHeroEvans** [comment]
Seems like a simple restart worked. No idea why this was even an issue on the first run in the first place.
