### ISSUE TITLE
Scrolling ground textures are not interpolated

### ISSUE THREAD

**Issue by garlic-os** [HarbourMasters/Starship#48]
Scrolling ground textures do not appear to be interpolated to higher framerates.

~~The scrolling texture on the ground in the last scene of the ending appears not to be interpolated to higher framerates:~~ Upon further inspection, this is the same for all of the scrolling textures used as floors in the game.

https://github.com/user-attachments/assets/2b91f6ea-2594-4816-ad1c-ce7ec45c32af

(The recording came out kind of choppy which defeats my point a little bit, sorry about that.)

**To reproduce**
Go to a level with a scrolling ground texture, like Venom 1, Macbeth, or the "running" part of the ending cutscene.

Tested in 144FPS.

**Comment by PurpleHato** [comment]
Hi! 
From what I understand, that scene uses a scrolling texture for the ground (and not an actual moving ground) 
However, LUS doesn’t support interpolating these types of effects, as it only handles matrix interpolation (moving 3d meshes)

**Comment by garlic-os** [comment]
Oh, the issue is with libultraship? In that case does somebody experienced with that project think it would be worth filing an issue there to request this?

**Comment by sonicdcer** [comment]
This is a known issue since LUS doesn't support interpolation for scrolling textures

**Comment by blackhand1001** [comment]
Does anyone know if there's an issue open on libultraships repo. We should definitely push to have this addressed there.

**Comment by SixelAlexiS90** [comment]
> This is a known issue since LUS doesn't support interpolation for scrolling textures

So this means that this will likely never going to be fixed? Having the ground running at 30 FPS is quite distracting considering how smooth is everything else.
