### ISSUE TITLE
World map camera is not interpolated

### ISSUE THREAD

**Issue by garlic-os** [HarbourMasters/Starship#49]
The movement you can do around the planets on the world map does not appear to be interpolated.

https://github.com/user-attachments/assets/25a25a6f-8dee-4405-b695-02d70657e5c6

I start selecting a mission at the end of the recording to demonstrate how much smoother other movements are.

Tested on Windows, 144FPS

**Comment by sonicdcer** [comment]
That's a performance issue on your end, idk what you're using to measure your frames but that isnt 144 FPS.
