### ISSUE TITLE
Crash upon starting Starship

### ISSUE THREAD

**Issue by Chustillo** [HarbourMasters/Starship#65]
[2024-12-25 18:46:30.294] [V:\Starship\libultraship\src\resource\archive\ArchiveManager.cpp:165] [info] Reading archive: C:\Users\USER1\Desktop\Rescate documentos\SF64\Starship-Centauri-Alfa-Windows\starship.otr
[2024-12-25 18:46:30.296] [V:\Starship\libultraship\src\resource\archive\OtrArchive.cpp:69] [info] Opened mpq file "C:\Users\USER1\Desktop\Rescate documentos\SF64\Starship-Centauri-Alfa-Windows\starship.otr"
[2024-12-25 18:46:30.296] [V:\Starship\libultraship\src\resource\archive\ArchiveManager.cpp:195] [info] Adding Archive C:\Users\USER1\Desktop\Rescate documentos\SF64\Starship-Centauri-Alfa-Windows\starship.otr to Archive Manager
[2024-12-25 18:46:30.523] [V:\Starship\libultraship\src\debug\CrashHandler.cpp:72] [critical] Exception: 0xe06d7363
Registers: 
RAX: 0x0000000000000000
RCX: 0x0000000200000001
RDX: 0x0000000000001010
RBX: 0x00007FF7D9B5E818
RSP: 0x0000004124BDF1F0
RBP: 0x0000004124BDF460
RSI: 0x0000004124BDF360
RDI: 0x0000000019930520
R9:  0x0000000100000060
R10: 0x0000006002000002
R11: 0x0000000000000000
R12: 0x0000000000000064
R13: 0x0000000000000000
R14: 0x0000000000000000
R15: 0x00007FF7D9A80DD0
RIP: 0x00007FFCD3BFB699
EFLAGS: 0x00000202
At RaiseExceptionAddr: 0x00007FFCD3BFB630
In: C:\WINDOWS\System32\KERNELBASE.dll
At RaiseExceptionAddr: 0x00007FFCD3BFB630
In: C:\Users\USER1\Desktop\Rescate documentos\SF64\Starship-Centauri-Alfa-Windows\Starship.exe
At RaiseExceptionAddr: 0x00007FFCD3BFB630
In: C:\Users\USER1\Desktop\Rescate documentos\SF64\Starship-Centauri-Alfa-Windows\Starship.exe
At RaiseExceptionAddr: 0x00007FFCD3BFB630
In: C:\Users\USER1\Desktop\Rescate documentos\SF64\Starship-Centauri-Alfa-Windows\Starship.exe
At RaiseExceptionAddr: 0x00007FFCD3BFB630
In: C:\Users\USER1\Desktop\Rescate documentos\SF64\Starship-Centauri-Alfa-Windows\Starship.exe
At RaiseExceptionAddr: 0x00007FFCD3BFB630
In: C:\Users\USER1\Desktop\Rescate documentos\SF64\Starship-Centauri-Alfa-Windows\Starship.exe
At RaiseExceptionAddr: 0x00007FFCD3BFB630
In: C:\Users\USER1\Desktop\Rescate documentos\SF64\Starship-Centauri-Alfa-Windows\Starship.exe
At RaiseExceptionAddr: 0x00007FFCD3BFB630
In: C:\Users\USER1\Desktop\Rescate documentos\SF64\Starship-Centauri-Alfa-Windows\Starship.exe
At RaiseExceptionAddr: 0x00007FFCD3BFB630
In: C:\Users\USER1\Desktop\Rescate documentos\SF64\Starship-Centauri-Alfa-Windows\Starship.exe
At RaiseExceptionAddr: 0x00007FFCD3BFB630
In: C:\Users\USER1\Desktop\Rescate documentos\SF64\Starship-Centauri-Alfa-Windows\Starship.exe
At RaiseExceptionAddr: 0x00007FFCD3BFB630
In: C:\Users\USER1\Desktop\Rescate documentos\SF64\Starship-Centauri-Alfa-Windows\Starship.exe
At RaiseExceptionAddr: 0x00007FFCD3BFB630
In: C:\Users\USER1\Desktop\Rescate documentos\SF64\Starship-Centauri-Alfa-Windows\Starship.exe
At RaiseExceptionAddr: 0x00007FFCD3BFB630
In: C:\Users\USER1\Desktop\Rescate documentos\SF64\Starship-Centauri-Alfa-Windows\Starship.exe
At RaiseExceptionAddr: 0x00007FFCD3BFB630
In: C:\Users\USER1\Desktop\Rescate documentos\SF64\Starship-Centauri-Alfa-Windows\Starship.exe
At BaseThreadInitThunkAddr: 0x00007FFCD4D57360
In: C:\WINDOWS\System32\KERNEL32.DLL
At RtlUserThreadStartAddr: 0x00007FFCD639CC70
In: C:\WINDOWS\SYSTEM32\ntdll.dll

**Comment by EdHerdman** [comment]
You have to run the "generate_otr.bat" file on the first run. Then you can run Starship.exe to launch afterwards.
https://github.com/HarbourMasters/Starship/issues/56

**Comment by Chustillo** [comment]
Yeah, already did it. Same issue.

**Comment by sonicdcer** [comment]
follow the readme, make sure your rom dump is the correct version needed and you have https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170 installed
