### ISSUE TITLE
All Range Mode - Powerups do not despawn

### ISSUE THREAD

**Issue by mattGGs** [HarbourMasters/Starship#73]
When in All Range Mode, powerups are supposed to despawn behind you shortly after passing over them. 

This includes:

- Silver Rings
- Lasers
- Bombs
- Star Rings (From Supply Box with Low Health)

Note: Gold Rings are not supposed to despawn behind you, but instead despawn on their own timer (currently works correctly)

See clip:
https://www.twitch.tv/safety_man/clip/BoringTameKittenSoBayed-aly8I1hvzgvykxbf?filter=clips&range=7d&sort=time

**Comment by sonicdcer** [comment]
This issue has been fixed in the latest commit, thank you for bringing it out to me.
