### ISSUE TITLE
NixOS Build

### ISSUE THREAD

**Issue by TheHans255** [HarbourMasters/Starship#76]
I'm trying to get a NixOS build for this project working (since I'm on NixOS 24.11). 

I'm starting by creating a `nix-shell` to see if I can follow the [build instructions](https://github.com/HarbourMasters/Starship/blob/main/docs/BUILDING.md), and I've been able to find equivalent packages for the entire dependency list except for the OpenGL bindings:

```
nix-shell -p gcc ninja lsb-release SDL2 libzip nlohmann_json tinyxml-2 spdlog boost
```

Predictably, the CMake configure command cannot find OpenGL:

```
$ cmake -H. -Bbuild-cmake -GNinja
-- The C compiler identification is GNU 13.3.0
-- The CXX compiler identification is GNU 13.3.0
-- The ASM compiler identification is GNU
-- Found assembler: /nix/store/kp2j7yn0wzwq5piy494r54dafrh83s6s-gcc-wrapper-13.3.0/bin/gcc
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /nix/store/kp2j7yn0wzwq5piy494r54dafrh83s6s-gcc-wrapper-13.3.0/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /nix/store/kp2j7yn0wzwq5piy494r54dafrh83s6s-gcc-wrapper-13.3.0/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /nix/store/ias7qy0iwfx6sbwhdc31r0pdhw2f9gcw-cmake-cursesUI-qt5UI-3.29.6/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_glx_LIBRARY
  OPENGL_INCLUDE_DIR)
Call Stack (most recent call first):
  /nix/store/ias7qy0iwfx6sbwhdc31r0pdhw2f9gcw-cmake-cursesUI-qt5UI-3.29.6/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /nix/store/ias7qy0iwfx6sbwhdc31r0pdhw2f9gcw-cmake-cursesUI-qt5UI-3.29.6/share/cmake-3.29/Modules/FindOpenGL.cmake:579 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:81 (find_package)

-- Configuring incomplete, errors occurred!
```

I did see in [the NixOS wiki](https://nixos.wiki/wiki/OpenGL) that there's a good deal of extra configuration needed to get OpenGL bindings to work, though nothing has changed after applying it.

**Comment by icecreammatt** [comment]
Thanks I was able to compile and run it after this and fixing some files that needed `%s` to fix compiler errors. Also had to lock FPS to30 so it wouldn't crash after pressing start.

**Comment by TheHans255** [comment]
Thanks, these instructions worked for me. I needed to use the `v1.0.0` release tag instead of the current `main` branch, but I imagine that's more or less intended.

However, I wasn't able to use the build to subsequently package a working AppImage (in order to run it on a Steam Deck - though the AppImage doesn't work on either machine, even with `steam-run`). I ended up setting up an Ubuntu Server VM to try building the AppImage there instead.

**Comment by jtrees** [comment]
Here's a bare bones flake I used to get it to compile, after applying @icecreammatt's fix [from here](https://github.com/HarbourMasters/Starship/issues/76#issuecomment-2564132258) by hand:

```nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable-small";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { nixpkgs, flake-utils, ... }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs { inherit system; };
      in
      {
        devShell = pkgs.mkShell {
          buildInputs = (with pkgs; [
            cmake
            libzip
            ninja
            nlohmann_json
            python3
            SDL2.dev
            spdlog.dev
            tinyxml-2
          ]);
        };
      });
}
```

**Comment by devusb** [comment]
I was also able to generally get this working as an actual package [here](https://github.com/devusb/nix-packages/blob/main/pkgs/Starship/default.nix). 

It's not the smoothest to run -- I put the `otr` file and `gamecontrollerdb.txt` in a directory, change to it, do `export SHIP_HOME=$PWD`, and then run the `Starship` binary as built by the derivation.
