### ISSUE TITLE
Controller "Input Editor" is a mess

### ISSUE THREAD

**Issue by BigheadSMZ** [HarbourMasters/Starship#81]
I have never experienced this much frustration setting up controllers. The interface somewhat makes sense in its approach, but also not really. When I first opened the menu, I could see what some buttons were mapped to. I removed the original mappings and create my own, and adding new mappings does not display the new mappings to the right of the button in the same way.

I have multiple controllers plugged in, one is a PS5 controller emulating a XB360 via DS4Windows, and the other controller is a Retro Fighters Brawler64. Whether I set the controller to XInput or DInput it fails in different ways. With XInput, the windows lock up and turn white with a message "Press any controller or move any axis on the controller for port 1". I don't understand why this is even a thing. Both controllers are working, yet this screen won't go away. I can verify inputs are working on both controllers via the "Game Controllers" window. Yet this screen doesn't detect any input. 

I managed to get rid of that window by right clicking the menu on the taskbar and clicking close. Currently there is 3x "Xbox 360 Controller" bars (blue, red, green) that all say "Disconnected" and I can't remove them. Currently, neither controller works when both are plugged in which makes no sense. If I plug one controller in, the input works. I clicked on the green one, now all of a sudden all the input boxes to the right of the button assignments reappeared. But the controller still doesn't work. I have no idea what is going on. If I plug both controllers in, neither of the controllers work. I'm hoping something with this gets fixed because currently the input system seems like kind of a mess.

Both controllers plugged in, working fine.
![image](https://github.com/user-attachments/assets/06c0715e-92c5-4a60-a7dd-2e68ecefa837)

This is my PS5 controller emulated as XB360. It's working fine.
![a](https://github.com/user-attachments/assets/341c4574-b1ef-48dd-a729-2b4a0e30c837)

This is my Brawler64 set in XInput mode, works fine.
![b](https://github.com/user-attachments/assets/8d773369-e0fc-437c-86cc-760e3e40ae60)

But when I load it up, frozen. No inputs work.
![image](https://github.com/user-attachments/assets/1069beea-26be-41c8-a72e-0d018bc0c2f4)

**Comment by DFAnk1** [comment]
This is a complete mess. Is there a way to map either ? Or can someone share the config file for real N64 controller ?

**Comment by Andrevus2** [comment]
Having issues with this thing myself, it does not recognize a single key on the keyboard while trying to change keybinds.

**Comment by Pliskin-Hunter** [comment]
Same here, nothing worked. I used joycons and it worked.

**Comment by zeroger** [comment]
I solved the problem by setting the controls to full screen mode

**Comment by Pliskin-Hunter** [comment]
It's working, you're a genius !

**Comment by sonicdcer** [comment]
The input editor is part of the Libultraship porting library, issues should be referred over that project.
