### ISSUE TITLE
Add support for US v1.0

### ISSUE THREAD

**Issue by flibitijibibo** [HarbourMasters/Starship#82]
Totally not urgent, but would be nice to have for those who only have 1.0 cartridges available.

If this is something that's mostly a matter of typing it out (i.e. "take the 1.1 config and update a wall of offsets with correct ones from Tool X") I can try to look at this, but I'm not sure how much actually changed beyond the high score fix.

**Comment by sonicdcer** [comment]
You'd need to make a complete disassembly of that version, identify all the same assets we have identified in 1.1 and then make ast_ yamls containing the addresses of all the assets in the game updated to 1.0.
