### ISSUE TITLE
NSO N64 Controller is misconfigured by default

### ISSUE THREAD

**Issue by CuddleBear92** [HarbourMasters/Starship#89]
The default controller config used when you use the Nintendo Switch Online N64 Controller is wrongly setup out of the gate.

Here is the correct config:
![image](https://github.com/user-attachments/assets/6186c19b-b0d0-4846-b568-4686db181c89)

**Comment by sonicdcer** [comment]
The software provides an initial config set by the libultraship library, you should use that menu to set your custom controller however you see fit.
