### ISSUE TITLE
Starship has crashed. Please upload the logs to the support channel in discord.

### ISSUE THREAD

**Issue by rogrtorr** [HarbourMasters/Starship#91]
"Starship has crashed. Please upload the logs to the support channel in discord."

I keep getting this error message when trying to run starship.exe. I followed the instructions correctly.

**Comment by BakerTheChef** [comment]
Same

**Comment by EdHerdman** [comment]
You can't start it just by running starship.exe. You have to run generate_otr.bat first, which generates the necessary files.
https://github.com/HarbourMasters/Starship/issues/56

**Comment by rogrtorr** [comment]
I followed the instructions, checked the hash, but after running the .bat file the cmd tells me the process is finished, but doesn't generate/extract the files. Then I get this message after running starship.exe
