### ISSUE TITLE
Stereo sound is phase-inverted?

### ISSUE THREAD

**Issue by withered-rose** [HarbourMasters/Starship#92]
I've noticed that when the game is in stereo audio mode (which happens to be the default), the left and right channels are out of phase with each other; at least for sound effects, not so sure about music. This inverted phase seems to make centered sounds seem "wider" than they should be, and might cause sound effects to cancel themselves out on certain setups. I don't think the game did this on original hardware.

Either way, the issue goes away when the setting is changed to "Headphones" or "Mono", so it's not the _biggest_ issue, but worth looking into.

**Comment by sonicdcer** [comment]
Can you provide a comparison of how it sounds and how you think it should sound?

**Comment by withered-rose** [comment]
https://github.com/user-attachments/assets/9c1668bb-8a4a-4701-9ff0-1cac14da9c61

Naturally, I recommend using headphones for this.

**Comment by sonicdcer** [comment]
> sf64.audio.bug.mp4 
> Naturally, I recommend using headphones for this.

Thank you very much, i really appreciate this. I'll take a deeper look into it!

**Comment by sonicdcer** [comment]
This issue has been fixed in the latest commit. Thank you!
